name: Brian Sooy
favicon: null
layout_spectrum: 0.22446
typography_spectrum: 0.77662
title: Author and Designer Brian Sooy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#83c441'
    - '#791e77'
    - '#e87c22'
    - '#007d8a'
  brandStrength: 0.75
  lightness: 0.125
  saturation: 0.6012675964739174
  rhythmicContrast: 0.5
purpose: []
